---
title: 'Conteneurs: Notions de base'
description: Principes de base et utilisation de conteneurs, application avec Docker.
categories:
  - Containers
  - Docker
  - I211
  - PO43
  - Lecture
provide_notes: true
provide_slides: false
jupyter: zsh
---

## Informations techniques 

::: {layout="[ 0.5, -0.05, 0.45 ]"}
:::: {#first-column}
{{< include ./quarto-utils/_tools_Git.qmd >}}
:::
:::: {#second-column}
{{< include ./quarto-utils/_tools_Docker.qmd >}}
::::
:::

{{< include ./quarto-utils/_init_Docker.qmd >}}

### Objectifs d'Apprentissage

Ce document est une introduction à l'utilisation des conteneurs pour isoler les composants d'une application. En pratique, nous utilisons [Docker](https://www.docker.com/).
L'objectif est de pouvoir produire des environnements de compilation et d'exécution d'applications répétables, versionnables et portables.

* Comprendre les concepts fondamentaux des conteneurs
* Maîtriser les commandes Docker de base
* Créer et gérer des conteneurs d'applications
* Utiliser des volumes et réseaux Docker

### Prérequis
* Linux: commandes de base
* Git: notions fondamentales
* Terminal: utilisation courante

## Vocabulaire

Conteneur 
: Un conteneur est une sorte de bac à sable (sandbox) qui isole un ensemble de processus du système en utilisant les namespaces du noyau linux et leur associe une carte réseau virtuelle. Un conteneur est l'instance d'une image. Généralement, un conteneur fournit un et un seul service.

Image
: Une image est système de fichier isolé qui contient tout ce qui est nécessaire pour l'exécution d'un conteneur. Elle contient aussi d'autres informations comme des metadonnées, des variables d'environnement ou la commande par défaut à exécuter. Souvent une image s'appuie sur une autre image à laquelle elle apporte des modificiations.

Container Daemon (containerd, Docker Daemon)
: Le container daemon est un serveur qui gère les images, les conteneurs, les réseaux et les volumes de stockage. Il peut communiquer avec d'autres container daemons et offre une API standard.

Docker Client
: Le docker client est un outils en ligne de commande pour envoyer des commandes à un ou plusieurs container daemons locaux ou distants. 


> Par exemple, un docker client peut demander à un container daemon d'exécuter une image ce qui produit un conteneur. Si l'image n'est pas disponible localement, elle est téléchargée par le container daemon depuis un registry.

## Installation

Docker peut être installé directement sous linux, il partage alors le noyau de l'hôte. Il peut aussi être installé dans une machine virtuelle Linux (sous Linux, Windows et MacOs) par exemple via [Docker Desktop](https://docs.docker.com/get-docker/).

## Exécuter un conteneur

La commande `docker container run` permet d'executer la commande par défaut d'une image dans un espace isolé. Si l'image n'est pas disponible pour le docker daemon, elle est téléchargée à partir d'un registry (par défaut [Docker Hub](http://hub.docker.com)).

Comme premier exemple, exécutons l'image [hello-world](https://hub.docker.com/_/hello-world) qui illustre ce fonctionnement (lire le résultat) :

```{zsh}
#| output: false
#| echo: false
#| tags: []
#| vscode: {languageId: zsh}
docker container run hello-world
```

Une commande docker commence par le type d'objet qu'elle manipule (`container`, `image`, ...) suivi d'une sous-commande. Par exemple, il est possible de demander au docker daemon de précharger ou de mettre à jour une image avec la sous-commande `pull`.

Pour télécharger ou mettre à jour [Alpine Linux](https://www.alpinelinux.org/) qui est une distribution linux très légère :

```{zsh}
#| output: false
#| echo: false
#| tags: []
#| vscode: {languageId: zsh}
docker image pull alpine
```

Le format du nom d'une image est `[registry_hostname[:port]][path]image_name[:tag]`. Si l'adresse du registry est omise c'est celle de dockerhub qui est utilisé (docker.io). Si l'image est "officielle" `path` peut-être omis et vaut `library`, sinon il s'agit généralement du compte de l'utilisateur qui fourni l'image. `tag` permet de différencier les versions d'une image, s'il est omis il vaut `latest`. 

Ainsi, le nom d'image `alpine` correspond en fait à `docker.io/library/alpine:latest`. La [documentation](https://hub.docker.com/_/alpine/tags) indique les tags existants. En production, pour obtenir des exécutions reproductibles il est conseillé de spécifier la version

Il est possible de choisir la commande à utiliser au lancement du container en l'indiquant après le nom de l'image. Des variables d'environnement peuvent êtrée crées dans le conteneur avec l'option `--env`.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker container run \
    alpine:3.17.2 uname -a
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker container run --env FIRSTNAME="John" --env NAME="Doe" \
    alpine:3.17.2 env
```

```{zsh}
#| output: true
#| echo: true
#| slideshow: {slide_type: subslide}
#| tags: []
#| vscode: {languageId: zsh}
docker container run \
    alpine:3.17.2 sh -c "echo 'Hi' > hello.txt ; cat hello.txt"
```

Si la commande est interactive (comme un shell bash par exemple il faut préciser `--interactive --tty` ou `-it`) pour utiliser l'entrée et la sortie standard. 

Il est aussi possible de donner un nom unique à conteneur qui peut être utilisé à la place de son ID avec l'option `--name`.

Dans l'exemple suivant `cat <<EOF` permet de simuler une saisie clavier pour exécuter plusieurs commandes dans un conteneur bash (mais pas dans une vraie console ou tty).
pour tester manuellement, il faut utiliser `docker run --interactive --tty --name my-bash ubuntu:22.04 bash` et exécuter les commandes. 

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
(
cat <<EOF
cd /root
ls -al
EOF
) | docker run --interactive --quiet --name my-bash ubuntu:22.04 bash - 
```

L'exécution d'un conteneur peut être faite tâche de fond avec l'option `--detach` ou `-d`.

Par exemple, pour lancer [redis](https://redis.com/), une base de donnée NoSQL de type clé/valeur :

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker run --quiet --detach --name my-redis redis:7.0.9
```

Les conteneurs produisent généralement le log du service sur la sortie standard. Quand `--detach` est utilisé la commande `logs` permet de le consulter (ajouter `-f` pour un suivi en continu).

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker logs my-redis
```

La sous-commande `ls` permet d'obtenir tous les conteneurs en cours d'exécution.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker container ls
```

La commande `ls -a` affiche aussi ceux qui se sont arrêtés.

```{zsh}
#| output: true
#| echo: true
#| slideshow: {slide_type: subslide}
#| tags: []
#| vscode: {languageId: zsh}
docker container ls -a
```

Un conteneur s'arrête quand sa commande termine. Il peut être arrêté manuellement avec la sous-commande `stop`.

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker container stop my-redis
```

Un conteneur arrêté peut être relancé avec les même paramètres avec la commande `start`.

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker container start my-redis
```

Un container arrêté peut être détruit avec la commande `rm` en indiquant son Id ou son nom.

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker rm my-bash
```

La commande `exec` permet d'exécuter une commande dans un conteneur en fonctionnement. Par exemple, pour utiliser l'interface en ligne de commande de redis depuis le conteneur `my-redis` (qui exécute déjà le serveur) pour ajouter une valeur de clé "a.b@x.fr".

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker exec my-redis redis-cli SET a.b@x.fr "Pierre,Durand,12"
```

L'option `--rm` de la commande `run` provoque la suppression du conteneur dès l'arrêt.

On peut alors créer un autre conteneur éphémère pour exécuter la commande de récupération d'une valeur de redis via le réseau (la partie réseau est expliquée plus tard) à partir de l'image du serveur. 

```{zsh}
#| output: true
#| echo: true
#| slideshow: {slide_type: subslide}
#| tags: []
#| vscode: {languageId: zsh}
docker run --rm --link my-redis redis:7.0.9 redis-cli -h my-redis GET a.b@x.fr
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker container ls 
```

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| user_expressions: []
#| vscode: {languageId: zsh}
docker container stop my-redis
docker container rm my-redis
```

Tous les containeurs arrêtés peuvent être supprimés avec la commande `container prune`.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker container prune --force
```

```{zsh}
#| output: true
#| echo: true
#| slideshow: {slide_type: subslide}
#| tags: []
#| vscode: {languageId: zsh}
docker container ls -a
```

## Gérer les images

Il est possible de lister ou supprimer les images disponibles localement avec la commande `image` et les sous-commandes `ls` et `rm`.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker image ls
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker image rm hello-world redis:7.0.9 alpine
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker image prune --force
```

## Volumes

Un conteneur est généralement éphémère et sans état pour pouvoir être arrêté et relancé sans perte de données. Les fichiers créés devant être persistants doivent donc l'être en dehors du conteneur. Pour cela, on utilise les montage de systeme d fichiers (bind mount) ou les volumes. 

Un bind volume, c'est-à-dire un montage du système de fichier de l'hôte vers un répertoire du conteneur, est définit avec l'option `-v <source>:<destination>` de la commande `run` que l'on peut uiliser plusieurs fois. Le chemin doit être absolu mais peut utiliser la variable d'environement `${PWD}` pour simuler un chemin relatif. 

Dans l'exemple suivant, un premier conteneur crée le fichier `text.txt` dans un volume monté de l'hôte (le répertoire `/tmp/mydata`) dans le conteneur (à l'emplacement `/data`). Le conteneur est ensuite détruit.
Un second conteneur monte le même répertoire de l'hôte (`/tmp/mydata` dans le nouveau conteneur mais dans `/databis`) et affiche le contenu.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker container run --rm \
    -v /tmp/mydata:/data \
    ubuntu:22.04 \
        bash -c "echo 'hello'>/data/test.txt"
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker container run --rm \
    -v /tmp/mydata:/databis \
    ubuntu:22.04 \
        cat /databis/test.txt
```

un volume peut aussi être un volume nommé géré par le docker daemon de façon transparente pour l'utilisateur. Il n'est alors plus aussi simple de partager des fichiers entre l'hôte et les conteneurs mais il n'y a plus de problème d'UID du propriétaire ni de droits. Il s'agit de la meilleure solution quand le docker daemon est exécuté sur un cluster et non sur une seule machine car alors le système de fichier peut être distribué.

L'exemple suivant exécute une base de données via l'image de [PostgreSQL](https://hub.docker.com/_/postgres) dans un premier conteneur. Le volume nommé `postgres-test-data` est monté dans le répertoire indiqué dans la documentation de l'image pour contenir la base de données (`/var/lib/postgresql/data`). Comme celui-ci est initialement vide, l'image est construite pour créer alors automatiquement une base de données à partir des variables d'environnement fournies. 

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker run -d --rm --quiet \
  --name postgres-test \
  --env POSTGRES_PASSWORD=mysecretpassword \
  -v postgres-test-data:/var/lib/postgresql/data \
  postgres:15.2
```

Il est possible de monter le même volume et un bind volume dans une autre conteneur par exemple pour faire une sauvegarde. En pratique, on préfère `pg_dump`, mais nous l'illustrons ici avec un simple tar. Dans le cas d'une base de données relationnelles l'arrêt du conteneur (ou un snapshot) est obligatoire pour garder la cohérence. 

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
container_name=postgres-test
[[ $(docker ps --filter "name=^/$container_name$" --format '{{.Names}}') == $name ]] ||
    docker container stop $container_name 
```

```{zsh}
#| output: true
#| echo: true
#| vscode: {languageId: zsh}
docker run --rm \
    -v postgres-test-data:/var/lib/postgresql/data \
    -v /tmp/backup:/backup \
    ubuntu:22.04 \
        tar zcf /backup/mydb.tar.gz /var/lib/postgresql/data 
```

Ensuite, un autre conteneur PostgreSQL peut être lancé en utilisant la même base.

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker run -d --rm \
  --name postgres-test \
  --env POSTGRES_PASSWORD=mysecretpassword \
  -v postgres-test-data:/var/lib/postgresql/data \
  postgres:15.2
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker logs postgres-test
```

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker stop postgres-test
```

Il est possible de lister et de supprimer les volumes avec les commandes `ls` et `rm`. Les volumes dont les noms sont des hachés appelés volumes anonymes sont présentés plus tard. 

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker volume ls
```

```{zsh}
#| output: true
#| echo: true
#| tags: [hide-output]
#| vscode: {languageId: zsh}
docker volume rm postgres-test-data
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker volume ls
```

### Réseau

Chaque conteneur dispose d'une carte réseau virtuelle et d'au moins une adresse IP. Un conteneur peut utiliser le réseau de l'hôte (`--host`) mais généralement il appartient à un ou plusieurs réseau virtuels. Si aucun n'est précisé expliciement, le conteneur appartient à un réseau par défaut. Comme les conteneurs sont éphémères et que les adresses IP changent, elles ne sont généralement pas utilisées directement. 

Les réseaux peuvent être créés, listés et détruits avec les commandes `network {create, ls, rm}`. 

Ainsi deux conteneurs qui exécutent un shell sont sur le réseau par défaut.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker run --quiet -dit --rm --name alpine1 alpine ash
docker run --quiet -dit --rm --name alpine2 alpine ash
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker network ls
```

La commande `docker inspect {container, volume, network} <name|ID>` permet de consulter le détails d'un objet docker. `jq` est un outils pour traiter des documents json.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker network inspect bridge|jq
```

Avec l'option `--link` lors du `run`un conteneur peut utiliser le nom d'un autre conteneur comme nom d'hôte. Ici on utilise un image qui contient des utilitaires réseaux.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker run --rm --quiet \
    --link alpine1 --link alpine2 \
    nicolaka/netshoot:latest \
        ping -c 1 alpine1 
```

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker container stop alpine1 alpine2
```

#### entre conteneurs

Pour que deux conteneurs puissent communiquer simplement, le mieux est qu'ils appartiennent à un même réseau et qu'ils soient nommés. Le nom du conteneur peut alors être utilisé comme un nom d'hôte sur le réseau.

si aucun réseau n'est précisé, le conteneur se trouvent dans le réseau par défaut. Il est alors obligatoire d'utiliser l'option `--link` qui est dépréciée. 

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker network create mynet
```

On peut alors exécuter un conteneur nommé `nginx-01` (il fournit un serveur web nginx) sur ce réseau avec l'option `--network`.

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker run --rm -d --name nginx-01 --quiet \
           --network mynet \
           nginx:1.23
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker network inspect mynet|jq
```

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output, remove]
#| vscode: {languageId: zsh}
docker run --quiet --detach --rm --name my-tshark \
           --network container:nginx-01 \
           nicolaka/netshoot:v0.9 \
             tshark -w /tmp/capture-output.pcap
```

ce serveur peut être atteint depuis un autre conteneur sur le même réseau en utilisant son nom. Ici on exécute la commande `pandoc` qui convertit un site web en texte :

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker run --quiet --network mynet --rm pandoc/core:3.5 --to plain http://nginx-01
```

```{zsh}
#| output: true
#| echo: true
#| tags: [remove]
#| vscode: {languageId: zsh}
sleep 1
docker exec -it my-tshark \
  tshark -r /tmp/capture-output.pcap -Y http
docker stop my-tshark
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker network ls
```

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker stop nginx-01
docker network rm mynet
```

### entre l'hôte et les conteneurs

Il est possible de mettre en place une redirection de ports entre l'hôte et les conteneurs avec l'option `-p <port hote>:<port conteneur>` à la création. Cela permet d'accéder aux services docker depuis l'hôte ou le réseau local. 

On peut donc lancer deux serveur nginx de deux versions différents qui écoutent chacun sur le port 80 de leur conteneur respectif mais qui sont accessibles depuis les port 8081 et 8082 de l'hôte.

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker run --quiet --rm -d --name nginx-01 -p 8081:80 nginx:1.22
docker run --quiet --rm -d --name nginx-02 -p 8082:80 nginx:1.23
```

Le nom `host.docker.internal` permet d'accéder à l'hôte depuis les conteneurs.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker run --rm --quiet \
    --add-host=host.docker.internal:host-gateway \
    curlimages/curl:7.88.1 --silent --head host.docker.internal:8081|head -n 2
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker run --rm --quiet \
    --add-host=host.docker.internal:host-gateway \
    curlimages/curl:7.88.1 --silent --head host.docker.internal:8082|head -n 2
```

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker stop nginx-01 nginx-02
```

## Illustration avec une base de données relationnelles

Pour illustrer les concepts précédents, nous allons créer une base de données Postgresql à partir de l'[image officielle](https://hub.docker.com/_/postgres) dans un sous-réseau `backnet` et dont les données seront persistées dans un volume nommé `postgres-01-data`.

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker network create backnet
```

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker run -d --rm \
  --name postgres-01 \
  --network backnet \
  --env POSTGRES_USER=dba \
  --env POSTGRES_PASSWORD=mysecretpassword \
  --env POSTGRES_DB=mydb \
  -v postgres-01-data:/var/lib/postgresql/data \
  postgres:15.2
```

Il est ensuite possible d'interroger cette base de données avec la commande `psql` exécutée dans un autre conteneur ephémère. 

```{zsh}
#| output: false
#| echo: false
#| tags: []
#| vscode: {languageId: zsh}
sleep 2 
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
sleep 2 
docker run --rm \
    --network backnet \
    --env PGPASSWORD=mysecretpassword \
    postgres:15.2 \
        psql -h postgres-01 -U dba mydb -c \
            "CREATE TABLE IF NOT EXISTS 
                    PERSON(ID serial PRIMARY KEY,NAME VARCHAR NOT NULL);
            INSERT INTO PERSON (NAME) VALUES ('Pierre');
            INSERT INTO PERSON (NAME) VALUES ('Marie');"
```

Le conteneur de la base de donnée peut être détruit (cf --rm) et un autre créé avec le même volume donc sans perte de données. 

```{zsh}
#| output: true
#| echo: true
#| tags: [remove-output]
#| vscode: {languageId: zsh}
docker stop postgres-01

docker run -d --rm \
  --name postgres-01 \
  --network backnet \
  --env POSTGRES_USER=dba \
  --env POSTGRES_PASSWORD=mysecretpassword \
  --env POSTGRES_DB=mydb \
  -v postgres-01-data:/var/lib/postgresql/data \
  postgres:15.2
```

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
sleep 2 

docker run --rm \
    --network backnet \
    --env PGPASSWORD=mysecretpassword \
    postgres:15.2 \
        psql -h postgres-01 -U dba mydb -c \
            "SELECT * FROM PERSON;"
```

On peut aussi utiliser un bind volume pour faire une sauvegarde sur l'hôte.

```{zsh}
#| output: true
#| echo: true
#| tags: []
#| vscode: {languageId: zsh}
docker run --rm \
    -v /tmp/backup:/backup \
    --network backnet \
    --env PGPASSWORD=mysecretpassword \
    postgres:15.2 \
        sh -c "pg_dumpall -h postgres-01 -U dba|gzip > \
               /backup/pg01-$(date +'%Y%m%d_%H%M%S').backup.gz"
```

Pour finir, le conteneur postgres-01 est arrêté et donc détruit, ainsi que le réseau.\
Dans notre exemple, le volume postgres-01-data est aussi détruit mais ***attention les données perdues***. 

```{zsh}
#| output: true
#| echo: true
#| vscode: {languageId: zsh}
docker stop postgres-01
docker network rm backnet
docker volume rm postgres-01-data
```


## Les essentiels

Cette section résume les commandes essentielles pour manipuler des conteneurs Docker.

### Démarrer un conteneur

Il est nécessaire de savoir démarrer, arrêter et supprimer un conteneur.

```{zsh}
#| output: true
#| echo: true
#| vscode: {languageId: zsh}
# Lancer un conteneur en arrière-plan
docker container run -d \
    --name web \
    --restart unless-stopped \
    -p 8080:80 \
    nginx:latest                    
```

```{zsh}
#| output: true
#| echo: true
#| vscode: {languageId: zsh}
# Lister les conteneurs en cours d'exécution
docker container ls
```

```{zsh}
#| output: true
#| echo: true
# Arrêter le conteneur
docker container stop web
```

```{zsh}
#| output: true
#| echo: true
# Supprimer en une commande
docker container rm web
```

### Volumes (Persistance)

Un conteneur DOIT être éphémère. Les données doivent être persistées dans un volume.
Les volumes peuvent être nommés (gérés par docker ) ou bindés (montés depuis l'hôte).

```{zsh}
#| output: true
#| echo: true
#| vscode: {languageId: zsh}
# Créer volume pour données PostgreSQL
docker volume create pgdata
# Lancer PostgreSQL avec volume et variables d'environnement
docker run -d --rm \
  --name db \
  -v pgdata:/var/lib/postgresql/data \
  -e POSTGRES_PASSWORD=secret \
  -e POSTGRES_USER=app \
  -e POSTGRES_DB=myapp \
  -p 55432:5432 \
  postgres:14-alpine
```

```{zsh}
#| output: true
#| echo: true
#| vscode: {languageId: zsh}
# Bind mount
docker run --rm -d \
  -v $(pwd)/app:/usr/share/nginx/html \
  --name web \
  nginx
```

```{zsh}
#| output: false
#| echo: false
#| vscode: {languageId: zsh}
docker container stop db
docker container stop web
```

### Réseaux

Chaque conteneur a sa propre carte réseau virtuelle. Les conteneurs peuvent être connectés à un ou plusieurs réseaux.
Les conteneurs d'un même réseau peuvent se joindre par leur nom.


```{zsh}
#| output: true
#| echo: true
#| vscode: {languageId: zsh}

# Créer réseau si besoin
docker network inspect app-net >/dev/null 2>&1 || \
  docker network create app-net

# Connecter conteneurs
docker container run -d --rm --quiet \
  --network app-net \
  --name web \
  nginx
docker container run -d --rm --quiet  \
  --network app-net \
  --name db \
  mysql
```

```{zsh}
#| output: false
#| echo: false
#| vscode: {languageId: zsh}
docker stop web db
```

Pour les services qui doivent être atteint depuis l'hôte ou le réseau local, il est possible de rediriger les ports de l'hôte vers les ports des conteneurs.


```{zsh}
#| output: true
#| echo: true
#| vscode: {languageId: zsh}
# Port Forwarding: HOST_PORT:CONTAINER_PORT
docker run -d --rm \
  --name web-port \
  -p 8080:80 \
  nginx
```

```{zsh}
#| output: false
#| echo: true
#| vscode: {languageId: zsh}
# Vérifier le mapping
# Test HTTP response with timeout
curl -m 5 -sI localhost:8080 | \
  grep -q "HTTP/" && \
      echo "✅ Port 8080 responds" || \
      echo "❌ Port 8080 not responding"
```
```{zsh}
#| output: true
#| echo: false
#| vscode: {languageId: zsh}
# Vérifier le mapping
# Test HTTP response with timeout
curl -m 5 -sI docker:8080 | grep -q "HTTP/" && echo "✅ Port 8080 responds" || echo "❌ Port 8080 not responding"
```

```{zsh}
#| output: false
#| echo: false
#| vscode: {languageId: zsh}
# Vérifier le mapping
docker container stop web-port
```
