---
title: Application à un projet Java
description: Exercices pratiques sur l'utilisation de conteneurs pour un projet Java.
categories:
    - Containers
    - Docker
    - Java
    - PostgreSQL
    - JPA
provide_notes: true
provide_slides: false    
jupyter: zsh
---


## Objectifs

Dans cet exercice pratique, nous allons:

1. Migrer une application Java/JPA de H2 vers PostgreSQL
2. Conteneuriser la base de données
3. Configurer un environnement de développement avec Docker Compose
4. Mettre en place des tests d'intégration

## Prérequis

### Environnement de développement
- Java 17 ou supérieur
- Maven 3.8+
- Docker et Docker Compose v2
- IntelliJ IDEA Ultimate ou VS Code avec:
  - Pack Extension Java
  - Dev Containers
  - Docker
  - Database Tools (IntelliJ IDEA)

## Étape 1: Analyse de l'existant

1. Identifier les configurations JPA actuelles:

- dans le fichier `pom.xml`pour le driver JDBC :

```xml
<!-- Exemple de configuration H2 actuelle -->
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>2.2.224</version>
</dependency>
```
et dans le fichier `persistance.xml`pour la connexion. 

Prévoir les adaptations. 

## Étape 2: Mise en place de PostgreSQL avec Docker

1. Executer postgresql en utilisant docker manuellement.

2. Confifurer l'IDE pour se connecter à la base de données.

3. Connecter l'application Java à la base de données PostgreSQL.

## Étape 3: Conteneuriser l'application Java

1. Créer un fichier `Dockerfile` pour l'application Java. Il devra contenir les étapes suivantes:
    - Produite l'artefact de l'application.
    - L'executer.

### Etape 4: Configurer Docker Compose

1. Créer le fichier Docker Compose :
    - demarrer la base de données PostgreSQL
    - demarrer l'application Java. L'image devra être construite si besoin.

## Étape 5: Dev. Containers (Optionnel)

1. Configurer l'environnement de développement avec Dev. Containers.

## Étape 6: Tests d'intégration (Optionnel)

1. Créer un profil de test avec TestContainers:

## Etape 7: Sécurité (Optionnel)

1. Ajouter un reverse proxy avec Traefik, apache ou nginx.
2. Configurer un certificat SSL et l'ajouter au reverse proxy.